__all__ = ['base_unit',
           'ground_unit',
           'water_unit',
           'air_unit',
           'static_unit',
           'tank',
           'footman',
           'jeep',
           'superjeep',
           'anti_armour',
           'battleship',
           'carrier',
           'artillery',
           'turret',
           'factory',
           'fighter',
           'anti_air',
           'bomber']
unit_types = {}
